### ISSUE TITLE
Where can I find Voicemeeter 3.1.1.3?

### ISSUE THREAD

**Issue by Spontini** [mframbou/Voicemeeter-Potato-Keygen#4]
First of all, thank you for creating this tool. I used to have a proper license for this software, but for some reason, they thought formatting the PC would revoke the license (the footprint doesn’t work—what a surprise). So, it’s always ethical to pirate such software. The only issue is that, as of now, the latest version on the VB-Audio website is 3.1.1.8, and I couldn’t find v3.1.1.3 anywhere. Where can I download it?"

**Comment by qyouqme** [comment]
> First of all, thank you for creating this tool. I used to have a proper license for this software, but for some reason, they thought formatting the PC would revoke the license (the footprint doesn’t work—what a surprise). So, it’s always ethical to pirate such software. The only issue is that, as of now, the latest version on the VB-Audio website is 3.1.1.8, and I couldn’t find v3.1.1.3 anywhere. Where can I download it?"

You just need change 3118 to 3113 in the download link .

**Comment by mframbou** [comment]
> First of all, thank you for creating this tool. I used to have a proper license for this software, but for some reason, they thought formatting the PC would revoke the license (the footprint doesn’t work—what a surprise). So, it’s always ethical to pirate such software. The only issue is that, as of now, the latest version on the VB-Audio website is 3.1.1.8, and I couldn’t find v3.1.1.3 anywhere. Where can I download it?"

There is the link for the 3.1.1.3 version: https://download.vb-audio.com/Download_CABLE/Voicemeeter8Setup_v3113.zip
